export const GET_USERS = 'GET_USERS'
export const SEARCH_USER = 'SEARCH_USER'
export const GET_USER = 'GET_USER'
export const GET_NAME = 'GET_NAME'
export const GET_SEARCHED_USER = 'GET_SEARCHED_USER'
export const LOADING = 'LOADING'